export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const ADD_MAIN_CATEGORY = "ADD_MAIN_CATEGORY";
export const ALL_SECTION = "ALL_SECTION";
export const ADD_SECTION_RESPONSE = "ADD_SECTION_RESPONSE";
export const ADD_SUB_SECTION_RESPONSE = "ADD_SUB_SECTION_RESPONSE";
export const RESET = "RESET";
