const descriptions = [
  "Soft and breathable cotton fabric for all-day comfort.",
  "Classic round neck design with a stylish print.",
  "Slim-fit T-shirt crafted for a modern, tailored look.",
  "Lightweight and moisture-wicking fabric keeps you cool.",
  "Premium quality fabric with high durability and softness.",
  "Trendy graphic print for a casual yet stylish look.",
  "Wrinkle-resistant fabric for an always-fresh appearance.",
  "Stretchable fabric ensures easy movement and flexibility.",
  "Eco-friendly organic cotton for a sustainable choice.",
  "Regular fit T-shirt, perfect for everyday wear.",
  "Fade-resistant colors that stay vibrant wash after wash.",
  "Quick-dry material, ideal for active lifestyles.",
  "Soft-wash treatment for extra comfort and a smooth feel.",
  "Breathable mesh paneling for enhanced ventilation.",
  "Contrast collar and sleeve design for a unique touch.",
  "Tagless label for an irritation-free experience.",
  "Designed with UV protection for outdoor activities.",
  "Double-stitched seams for added durability.",
  "Minimalist solid color design for versatile styling.",
  "Premium combed cotton for superior softness.",
  "Anti-odor technology keeps you feeling fresh.",
  "Super stretch fabric for unrestricted movement.",
  "Ribbed crew neck for a snug and comfortable fit.",
  "Vintage-inspired faded print for a retro feel.",
  "Cool pastel shades for a refreshing summer vibe.",
  "Water-resistant coating for added durability.",
  "High-density print for a premium look and feel.",
  "Casual yet elegant design suitable for all occasions.",
  "Soft inner lining for extra comfort in colder months.",
  "Athleisure-inspired design, perfect for workouts.",
  "Sleek monochrome style for a sophisticated look.",
  "Stylish embroidery details for a premium touch.",
  "Oversized fit for a relaxed and trendy appeal.",
  "100% recycled fabric, a step towards sustainability.",
  "Side slits for better mobility and a fashionable edge.",
  "Two-tone contrast for a stylish streetwear look.",
  "Raglan sleeves for enhanced comfort and flexibility.",
  "Tie-dye pattern for a bold, eye-catching statement.",
  "Thermal-regulating fabric for year-round comfort.",
  "Soft-touch fabric with a luxurious feel.",
  "Minimalistic logo branding for a clean aesthetic.",
  "Classic striped pattern for a timeless appeal.",
  "Pre-shrunk fabric to maintain perfect fit after wash.",
  "Graphic typography print for a trendy statement.",
  "Easy-care material with minimal ironing required.",
  "Hooded T-shirt for an urban streetwear vibe.",
  "Geometric prints for a bold and modern style.",
  "Longline T-shirt with a contemporary silhouette.",
  "Super lightweight fabric for ultimate comfort.",
  "Camo print for a rugged and stylish outdoor look.",
];
const brands = [
  "Nike",
  "Adidas",
  "Puma",
  "Reebok",
  "Under Armour",
  "New Balance",
  "Asics",
  "Fila",
  "Skechers",
  "Converse",
  "Vans",
  "Levi's",
  "Wrangler",
  "Lee",
  "Pepe Jeans",
  "Diesel",
  "Jack & Jones",
  "Tommy Hilfiger",
  "Calvin Klein",
  "Gucci",
  "Louis Vuitton",
  "H&M",
  "Zara",
  "Forever 21",
  "GAP",
  "Uniqlo",
  "Burberry",
  "Armani",
  "Versace",
  "Dolce & Gabbana",
  "Balenciaga",
  "Prada",
  "Hugo Boss",
  "Lacoste",
  "Superdry",
  "Columbia",
  "North Face",
  "Patagonia",
  "Timberland",
  "Carhartt",
  "Champion",
  "Volcom",
  "Billabong",
  "Quiksilver",
  "Ralph Lauren",
  "American Eagle",
  "Abercrombie & Fitch",
  "Express",
  "Hollister",
  "Aeropostale",
  "Brooks Brothers",
  "Banana Republic",
  "Dockers",
  "Guess",
  "Esprit",
  "Tom Tailor",
  "Marks & Spencer",
  "Ted Baker",
  "G-Star Raw",
  "Ben Sherman",
  "Paul Smith",
  "Eddie Bauer",
  "L.L.Bean",
  "Jockey",
  "Hanes",
  "Fruit of the Loom",
  "Russell Athletic",
  "Gildan",
  "Hurley",
  "Oakley",
  "RVCA",
  "Element",
  "Dickies",
  "Wrangler",
  "John Players",
  "Mufti",
  "Allen Solly",
  "Raymond",
  "Park Avenue",
  "Van Heusen",
  "Peter England",
  "Louis Philippe",
  "Blackberrys",
  "Arrow",
  "Celio",
  "Indian Terrain",
  "Ray-Ban",
  "Spykar",
  "U.S. Polo Assn.",
  "French Connection",
  "Ed Hardy",
  "Beverly Hills Polo Club",
  "Flying Machine",
  "Roadster",
  "Mast & Harbour",
  "Wrogn",
  "HRX",
  "Moda Rapido",
  "Highlander",
  "HERE&NOW",
];
const products = [
  {
    id: 1,
    name: "Men's Cotton T-Shirt",
    brand: "Nike",
    description: "Premium quality cotton T-shirt with breathable fabric.",
    price: 999,
    discount: 20, // Percentage
    finalPrice: 799, // After discount
    stock: 50,
    rating: 4.5,
    image:
      "https://assets.myntassets.com/dpr_2,q_60,w_210,c_limit,fl_progressive/assets/images/2024/NOVEMBER/20/sCEVIRwC_612a23e3cf544ee78a96c0a17b21c956.jpg,",
  },
  {
    id: 2,
    name: "Men's Casual Polo Shirt",
    brand: "Puma",
    description: "Classic polo shirt for a smart casual look.",
    price: 1299,
    discount: 15,
    finalPrice: 1104,
    stock: 30,
    rating: 4.2,
  },
  {
    id: 3,
    name: "Slim Fit Round Neck T-Shirt",
    brand: "Adidas",
    description: "Trendy and comfortable round-neck T-shirt.",
    price: 899,
    discount: 10,
    finalPrice: 809,
    stock: 70,
    rating: 4.7,
  },
  // Add more products here
];

export const generateProducts = (count = 5000) => {
  const sampleProducts = [...products];
  let generated = [];

  for (let i = 0; i < count; i++) {
    let product = { ...sampleProducts[i % sampleProducts.length] };
    product.id = i + 1;
    product.stock = Math.floor(Math.random() * 100) + 1;
    product.rating = (Math.random() * 5).toFixed(1);
    product.description =
      descriptions[Math.floor(Math.random() * descriptions.length)];
    product.brand = brands[Math.floor(Math.random() * brands.length)];
    generated.push(product);
    product.image =
      "https://assets.myntassets.com/dpr_2,q_100,w_110,c_limit,fl_progressive/assets/images/2024/SEPTEMBER/14/V4BV6q1B_7f398a35c63643d88c071a2909ddb191.jpg";
  }

  return generated;
};

export const brandList = [
  { title: "Allen Solly", count: 1228 },
  { title: "ADRO", count: 1038 },
  { title: "ADIDAS", count: 878 },
  { title: "Arrow Sport", count: 764 },
  { title: "AUSK", count: 707 },
  { title: "Aeropostale", count: 703 },
  { title: "Arrow", count: 576 },
  { title: "ASICS", count: 554 },
  { title: "appulse", count: 501 },
  { title: "Ajile by Pantaloons", count: 466 },
  { title: "AMERICAN EAGLE OUTFITTERS", count: 422 },
  { title: "Andamen", count: 395 },
  { title: "Aero Armour", count: 348 },
  { title: "AMSWAN", count: 180 },
  { title: "AD By Arvind", count: 177 },
  { title: "Adobe", count: 168 },
  { title: "AUXAMIS", count: 165 },
  { title: "ADIDAS Originals", count: 163 },
  { title: "Antony Morato", count: 155 },
  { title: "ATHLISIS", count: 132 },
  { title: "Allen Solly Sport", count: 132 },
  { title: "Arrow New York", count: 129 },
  { title: "ARMISTO", count: 125 },
  { title: "AUSTIVO", count: 123 },
  { title: "Alan Jones", count: 105 },
  { title: "ARISE", count: 101 },
  { title: "ATICX", count: 98 },
  { title: "ARRAY", count: 94 },
  { title: "ARBOUR", count: 87 },
  { title: "AXMANN", count: 79 },
  { title: "ALARM", count: 75 },
  { title: "ARIIX", count: 72 },
  { title: "ALTINYILDIZ CLASSICS AC Co.", count: 67 },
  { title: "Alcis", count: 66 },
  { title: "AESTHETIC NATION", count: 60 },
  { title: "Athflex", count: 59 },
  { title: "Allen Cooper", count: 59 },
  { title: "Aesthetic Bodies", count: 59 },
  { title: "Austin wood", count: 57 },
  { title: "ALCOTT", count: 49 },
  { title: "Ascend 47", count: 47 },
  { title: "ARDEUR", count: 40 },
  { title: "ARTICALE", count: 39 },
  { title: "Antiloop", count: 38 },
  { title: "ABSOLUTE DEFENSE", count: 36 },
  { title: "AIR GARB", count: 35 },
  { title: "AVVA", count: 30 },
  { title: "ARMENOR", count: 30 },
  { title: "Allen Solly Tribe", count: 28 },
  { title: "AVEJO", count: 26 },
  { title: "abof", count: 26 },
  { title: "Asterisk", count: 25 },
  { title: "Anax Aesthetics", count: 24 },
  { title: "ABLING", count: 24 },
  { title: "ALMOST SANE", count: 23 },
  { title: "AYCS", count: 22 },
  { title: "Artengo By Decathlon", count: 22 },
  { title: "ATTIITUDE", count: 17 },
  { title: "Albion", count: 17 },
  { title: "Aux India Company", count: 16 },
  { title: "Aristitch", count: 16 },
  { title: "ALIZA", count: 16 },
  { title: "AUSTIEX", count: 14 },
  { title: "ARISTOBRAT", count: 13 },
  { title: "Anta", count: 12 },
  { title: "ANML", count: 12 },
  { title: "A & Y", count: 12 },
  { title: "ATTITUDE START OF FASHION", count: 10 },
  { title: "AR 9", count: 10 },
  { title: "all yours", count: 10 },
  { title: "AGUANTE", count: 10 },
  { title: "ADORATE", count: 10 },
  { title: "AECK", count: 9 },
  { title: "ARTLESS", count: 8 },
  { title: "AMMARZO", count: 8 },
  { title: "Altstreetz", count: 8 },
  { title: "Autumn Hues", count: 7 },
  { title: "Arya Giri", count: 7 },
  { title: "Afalusz", count: 7 },
  { title: "ALAKH HUB", count: 5 },
  { title: "A AND K", count: 5 },
  { title: "aLL", count: 4 },
  { title: "ATLANCE", count: 3 },
  { title: "AAITHAN", count: 3 },
  { title: "Aventura Outfitters", count: 2 },
  { title: "American Crew", count: 2 },
  { title: "Albion By CnM", count: 2 },
  { title: "Aerio", count: 2 },
  { title: "Arrow Blue Jean Co.", count: 1 },
  { title: "ACTOHOLIC", count: 1 },
];

export const colorsData = [
  { title: "Black", count: 32400, colorCode: "#000000" },
  { title: "White", count: 23156, colorCode: "#FFFFFF" },
  { title: "Blue", count: 22313, colorCode: "#0000FF" },
  { title: "Green", count: 14056, colorCode: "#008000" },
  { title: "Navy Blue", count: 13898, colorCode: "#000080" },
  { title: "Grey", count: 11645, colorCode: "#808080" },
  { title: "Red", count: 8776, colorCode: "#FF0000" },
  { title: "Yellow", count: 6394, colorCode: "#FFFF00" },
  { title: "Beige", count: 6007, colorCode: "#F5F5DC" },
  { title: "Olive", count: 5528, colorCode: "#808000" },
  { title: "Maroon", count: 5431, colorCode: "#800000" },
  { title: "Pink", count: 4936, colorCode: "#FFC0CB" },
  { title: "Brown", count: 4447, colorCode: "#A52A2A" },
  { title: "Orange", count: 3503, colorCode: "#FFA500" },
  { title: "Purple", count: 3118, colorCode: "#800080" },
  { title: "Mustard", count: 2591, colorCode: "#FFDB58" },
  { title: "Teal", count: 2439, colorCode: "#008080" },
  { title: "Off White", count: 2422, colorCode: "#FAF9F6" },
  { title: "Peach", count: 2171, colorCode: "#FFDAB9" },
  { title: "Multi", count: 1609, colorCode: "#D3D3D3" }, // Placeholder color
  { title: "Lavender", count: 1595, colorCode: "#E6E6FA" },
  { title: "Turquoise Blue", count: 1579, colorCode: "#40E0D0" },
  { title: "Cream", count: 1455, colorCode: "#FFFDD0" },
  { title: "Charcoal", count: 1425, colorCode: "#36454F" },
  { title: "Sea Green", count: 1402, colorCode: "#2E8B57" },
  { title: "Rust", count: 1362, colorCode: "#B7410E" },
  { title: "Grey Melange", count: 1291, colorCode: "#A0A0A0" },
  { title: "Burgundy", count: 985, colorCode: "#800020" },
  { title: "Mauve", count: 647, colorCode: "#E0B0FF" },
  { title: "Coral", count: 627, colorCode: "#FF7F50" },
  { title: "Khaki", count: 500, colorCode: "#C3B091" },
  { title: "Lime Green", count: 438, colorCode: "#32CD32" },
  { title: "Coffee Brown", count: 344, colorCode: "#6F4E37" },
  { title: "Gold", count: 262, colorCode: "#FFD700" },
  { title: "Taupe", count: 259, colorCode: "#483C32" },
  { title: "Rose", count: 179, colorCode: "#FF007F" },
  { title: "Fluorescent Green", count: 168, colorCode: "#00FF00" },
  { title: "Violet", count: 144, colorCode: "#8F00FF" },
  { title: "Camel Brown", count: 116, colorCode: "#C19A6B" },
  { title: "Tan", count: 114, colorCode: "#D2B48C" },
  { title: "Steel", count: 85, colorCode: "#71797E" },
  { title: "Silver", count: 72, colorCode: "#C0C0C0" },
  { title: "Magenta", count: 67, colorCode: "#FF00FF" },
  { title: "Nude", count: 36, colorCode: "#F2D2BD" },
  { title: "Skin", count: 35, colorCode: "#FFDAB9" },
  { title: "Metallic", count: 29, colorCode: "#B0B0B0" }, // Placeholder
  { title: "Assorted", count: 25, colorCode: "#D3D3D3" }, // Placeholder
  { title: "Rose Gold", count: 23, colorCode: "#B76E79" },
  { title: "Copper", count: 11, colorCode: "#B87333" },
  { title: "Champagne", count: 4, colorCode: "#F7E7CE" },
  { title: "Bronze", count: 4, colorCode: "#CD7F32" },
  { title: "Transparent", count: 1, colorCode: "transparent" },
];
